# Generated by Django 6.0.1 on 2026-01-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_menu_image_alter_menu_name_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='choose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='Menu.category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
