# Generated by Django 6.0.1 on 2026-01-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_code', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Menu.cart')),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
    ]
